"""
Data models and schemas for the E-Commerce Knowledge Graph.
Defines entity types, attributes, relationship types, and query specifications.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class Brand(BaseModel):
    id: str
    name: str
    country: str
    rating: float = 4.5


class Category(BaseModel):
    id: str
    name: str
    department: str


class Vendor(BaseModel):
    id: str
    name: str
    country: str
    lead_time_days: int = 5


class Product(BaseModel):
    id: str
    name: str
    price: float
    brand_id: str
    category_id: str
    vendor_id: str
    stock: int = 100


class OrderItem(BaseModel):
    product_id: str
    quantity: int = 1
    unit_price: float


class Order(BaseModel):
    id: str
    customer_id: str
    order_date: str
    items: List[OrderItem]
    total_amount: float
    status: str = "DELIVERED"


class Customer(BaseModel):
    id: str
    name: str
    email: str
    loyalty_tier: str = "Standard"


# Graph Query and Retrieval Schemas
class GraphQuerySpec(BaseModel):
    """
    Structured query generated by the LLM from natural language.
    Specifies targets, filters, and multi-hop traversals.
    """
    intent: str = Field(..., description="Action/intent of the query, e.g. 'find_products_by_brand_and_vendor'")
    target_entity: str = Field(..., description="Primary entity type to return (Product, Brand, Category, Vendor, Order, Customer, All)")
    filters: Dict[str, Any] = Field(default_factory=dict, description="Attribute filters on nodes, e.g. {'name': 'Banana'}")
    traversal: List[Dict[str, str]] = Field(
        default_factory=list,
        description="List of relationship hops, e.g. [{'relation': 'PRODUCED_BY', 'target_type': 'Brand', 'target_name': 'TechCore'}]"
    )
    aggregation: Optional[str] = Field(None, description="Optional aggregation, e.g. 'count', 'max_value', 'group_by'")


class RetrievalResult(BaseModel):
    """
    Structured response returned by the Graph Retrieval Layer.
    """
    query_executed: Dict[str, Any]
    matched_nodes: List[Dict[str, Any]]
    relationships: List[Dict[str, Any]]
    summary_facts: List[str]
    is_empty: bool = False


class PipelineResponse(BaseModel):
    """
    Full end-to-end trace of a user question through the system.
    """
    question: str
    graph_query: Dict[str, Any]
    retrieved_data: RetrievalResult
    final_answer: str
    grounded: bool
    model_used: str
